// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAPM.ResourceRegistryMS.Api.Migrations
{
    [DbContext(typeof(ResourceRegistryDbContext))]
    partial class ResourceRegistryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAPM.ResourceRegistryMS.Api.Models.Peer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Peers");
                });

            modelBuilder.Entity("DAPM.ResourceRegistryMS.Api.Models.Pipeline", b =>
                {
                    b.Property<Guid>("PeerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PeerId", "RepositoryId", "Id");

                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("DAPM.ResourceRegistryMS.Api.Models.Repository", b =>
                {
                    b.Property<Guid>("PeerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PeerId", "Id");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("DAPM.ResourceRegistryMS.Api.Models.Resource", b =>
                {
                    b.Property<Guid>("PeerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PeerId", "RepositoryId", "Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("DAPM.ResourceRegistryMS.Api.Models.ResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResourceTypes");
                });

            modelBuilder.Entity("DAPM.ResourceRegistryMS.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Organization")
                        .HasColumnType("uuid");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.Property<int>("accepted")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11d98331-792a-45b8-85f8-0b273810d7cb"),
                            FirstName = "admin",
                            HashPassword = "$2a$12$Jligef.ByeRACdblRiMuDejgNYXlUBZWfCSD3wTZ029g5MF/x8cDa",
                            LastName = "admin",
                            Mail = "admin@email.ch",
                            Organization = new Guid("c756cd4d-7d1b-49df-a206-6296d361c46c"),
                            UserRole = 1,
                            accepted = 1
                        });
                });

            modelBuilder.Entity("DAPM.ResourceRegistryMS.Api.Models.Pipeline", b =>
                {
                    b.HasOne("DAPM.ResourceRegistryMS.Api.Models.Peer", "Peer")
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAPM.ResourceRegistryMS.Api.Models.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("PeerId", "RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DAPM.ResourceRegistryMS.Api.Models.Repository", b =>
                {
                    b.HasOne("DAPM.ResourceRegistryMS.Api.Models.Peer", "Peer")
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("DAPM.ResourceRegistryMS.Api.Models.Resource", b =>
                {
                    b.HasOne("DAPM.ResourceRegistryMS.Api.Models.Peer", "Peer")
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAPM.ResourceRegistryMS.Api.Models.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("PeerId", "RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");

                    b.Navigation("Repository");
                });
#pragma warning restore 612, 618
        }
    }
}
